import { PROPERTY_TYPES } from "./PBPropertyTypes";

const STYLE_DEFS = { 
  append: true,
  propAccessor: "style",
  propIsObj: true,
}
export const DEFAULT_PROPERTIES = [
  {
    _type: PROPERTY_TYPES.INPUT,
    text: "Text Content",
    name: "text",
    // placeholder: "0",
    type: "text",
    label: "Add text",
    placeholder: "Enter text here...",
    propAccessor: "text",
  },
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    text: "Dimensions",
    group: [
      {
        ...STYLE_DEFS,
        name: "width",
        placeholder: "0",
        type: "number",
        label: "Width",
        value: 32,
        accessor: "width",
        unit: "px",
      },
      {
        ...STYLE_DEFS,
        name: "height",
        placeholder: "0",
        type: "number",
        label: "Height",
        value: 32,
        accessor: "height",
        unit: "px",
      },
    ],
  },
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    name: "padding",
    text: "Padding (%)",
    group: [
      {
        ...STYLE_DEFS,
        label: "Left",
        placeholder: "0",
        type: "number",
        name: "pl",
        cssKey: "paddingLeft",
      },
      {
        ...STYLE_DEFS,
        label: "Right",
        placeholder: "0",
        type: "number",
        name: "pr",
        accessor: "paddingRight",
      },
      {
        ...STYLE_DEFS,
        label: "Top",
        placeholder: "0",
        type: "number",
        name: "pt",
        accessor: "paddingTop",
      },
      {
        ...STYLE_DEFS,
        label: "Bottom",
        placeholder: "0",
        type: "number",
        name: "pb",
        accessor: "paddingBottom",
      },
    ],
  },
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    name: "margin",
    text: "Margin (%)",
    group: [
      {
        ...STYLE_DEFS,
        label: "Left",
        placeholder: "0",
        type: "number",
        name: "pl",
        accessor: "marginLeft",
      },
      {
        ...STYLE_DEFS,
        label: "Right",
        placeholder: "0",
        type: "number",
        name: "pr",
        accessor: "marginRight",
      },
      {
        ...STYLE_DEFS,
        label: "Top",
        placeholder: "0",
        type: "number",
        name: "pt",
        accessor: "marginTop",
      },
      {
        ...STYLE_DEFS,
        label: "Bottom",
        placeholder: "0",
        type: "number",
        name: "pb",
        accessor: "marginBottom",
      },
    ],
  },
  {
    ...STYLE_DEFS,
    _type: PROPERTY_TYPES.COLOR_PICKER,
    name: "background",
    text: "Background Color",
    accessor: "background",
    value: "#dddddd",
  },
  {
    ...STYLE_DEFS,
    _type: PROPERTY_TYPES.DROPDOWN,
    name: "v-alignment",
    text: "Vertical Alignment",
    accessor: "justifyContent",
    value: "flex-start",
    data: [
      { name: "Center", value: "center" },
      { name: "Top", value: "flex-start" },
      { name: "Bottom", value: "flex-end" },
    ],
  },
  {
    ...STYLE_DEFS,
    _type: PROPERTY_TYPES.DROPDOWN,
    name: "h-alignment",
    text: "Horizontal Alignment",
    accessor: "alignItems",
    value: "flex-start",
    data: [
      { name: "Center", value: "center" },
      { name: "Left", value: "flex-start" },
      { name: "Right", value: "flex-end" },
    ],
  },
];
export const FAKE_PROPERTIES = [
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    text: "Dimensions (px)",
    group: [
      { name: "width", placeholder: "0", type: "number", label: "Width", value: 32 },
      { name: "height", placeholder: "0", type: "number", label: "Height", value: 32 },
    ],
  },
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    name: "padding",
    text: "Padding (%)",
    group: [
      { label: "Left", placeholder: "0", type: "number", name: "pl" },
      { label: "Right", placeholder: "0", type: "number", name: "pr" },
      { label: "Top", placeholder: "0", type: "number", name: "pt" },
      { label: "Bottom", placeholder: "0", type: "number", name: "pb" },
    ],
  },
  {
    _type: PROPERTY_TYPES.INPUT_GROUP,
    name: "margin",
    text: "Margin (%)",
    group: [
      { label: "Left", placeholder: "0", type: "number", name: "pl" },
      { label: "Right", placeholder: "0", type: "number", name: "pr" },
      { label: "Top", placeholder: "0", type: "number", name: "pt" },
      { label: "Bottom", placeholder: "0", type: "number", name: "pb" },
    ],
  },
  {
    _type: PROPERTY_TYPES.BACKGROUND_PICKER,
    name: "background",
    text: "Background",
  },
];
